// <auto-generated />
namespace CaelumEstoque.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Protecao1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Protecao1));
        
        string IMigrationMetadata.Id
        {
            get { return "201710212345208_Protecao1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
