// <auto-generated />
namespace CaelumEstoque.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class eareae : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(eareae));
        
        string IMigrationMetadata.Id
        {
            get { return "201710212328496_eareae"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
