// <auto-generated />
namespace LocadoraCarro.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ClasseId_tabela_Modelo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClasseId_tabela_Modelo));
        
        string IMigrationMetadata.Id
        {
            get { return "201801252037049_ClasseId_tabela_Modelo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
